<?php

namespace Blog\GeneralBundle\Repository;

/**
 * Article2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Article2Repository extends \Doctrine\ORM\EntityRepository
{
}
