services:
#    page_pages.example:
#        class: Page\PagesBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    Page\PagesBundle\DataFixtures\ORM\PagesData:
      tags: [doctrine.fixture.orm]
