<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * PoduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoduitRepository extends \Doctrine\ORM\EntityRepository
{
  
}
