<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends \Doctrine\ORM\EntityRepository
{
  public function byCategorie1(){

    return $this->getEntityManager()
     ->createQuery(
         "SELECT p FROM EcommerceEcommerceBundle:Produits p WHERE p.categorie='Carpets'"
     )
     ->getResult();}

 public function byCategorie2(){

   return $this->getEntityManager()
    ->createQuery(
        "SELECT p FROM EcommerceEcommerceBundle:Produits p WHERE p.categorie='Accesories'"
    )
    ->getResult();}
public function byCategorie3(){

  return $this->getEntityManager()
   ->createQuery(
       "SELECT p FROM EcommerceEcommerceBundle:Produits p WHERE p.categorie='Clutchs'"
   )
   ->getResult();}

public function byCategorie4(){

 return $this->getEntityManager()
  ->createQuery(
      "SELECT p FROM EcommerceEcommerceBundle:Produits p WHERE p.categorie='Foot Wear'"
  )
  ->getResult();}

  public function findArray($array){
    $qb=$this->createQueryBuilder('u')
             ->Select('u')
             ->Where('u.id IN (:array)')
             ->setParameter('array',$array);
             return $qb->getQuery()->getResult();
             }
}
