<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * PrroduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrroduitsRepository extends \Doctrine\ORM\EntityRepository
{
}
