<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * userssRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userssRepository extends \Doctrine\ORM\EntityRepository
{
}
